# Generated by Django 5.0 on 2023-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file1",
                    models.FileField(blank=True, null=True, upload_to="users/videos"),
                ),
                (
                    "file2",
                    models.FileField(blank=True, null=True, upload_to="users/videos"),
                ),
                (
                    "file3",
                    models.FileField(blank=True, null=True, upload_to="users/videos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_uploaded_files",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="uploadedfiles",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="uploaded_files", to="api.userfiles"
            ),
        ),
    ]
