# Generated by Django 5.0 on 2023-12-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userfiles_user_uploadedfiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="uploadedfiles",
        ),
        migrations.AddField(
            model_name="userfiles",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="file1",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="file2",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="file3",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
    ]
